export const configuratorConstants = {
    GET_CONFIGURATOR_REQUEST: 'GET_CONFIGURATOR_REQUEST',
    GET_CONFIGURATOR_SUCCESS: 'GET_CONFIGURATOR_SUCCESS',
    GET_CONFIGURATOR_FAILURE: 'GET_CONFIGURATOR_FAILURE',
};