export const testimonialConstants = {
    GET_TESTIMONIAL_REQUEST: 'GET_TESTIMONIAL_REQUEST',
    GET_TESTIMONIAL_SUCCESS: 'GET_TESTIMONIAL_SUCCESS',
    GET_TESTIMONIAL_FAILURE: 'GET_TESTIMONIAL_FAILURE',
};